name: hadar_program
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
 
  flutter_datetime_picker: ^1.5.1
  logger: ^2.0.2
  flutter_local_notifications: ^15.1.1
  timezone: ^0.9.2
  flutter_timezone: ^1.0.7
  rxdart: ^0.27.7
  # native
  file_picker: ^5.5.0
  url_launcher: ^6.1.14
  widget_to_marker: ^1.0.4
  http_parser: ^4.0.2

  # location
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  image_picker: ^1.0.2


  # state
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.4
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.0.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  bot_toast: ^4.1.1
  skeletonizer: ^0.8.0

  # util
  collection: ^1.17.2
  timeago: ^3.5.0
  faker: ^2.1.0
  kosher_dart: ^2.0.16

  # routing
  go_router: ^10.1.2

  # networking
  dio: ^5.4.1
  requests_inspector: ^4.0.0
  http: ^1.1.0 # todo: remove

  # integrations
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3

  # icons
  fluentui_system_icons: ^1.1.234

  # widgets
  flutter_easyloading: ^3.0.5 # todo: remove
  syncfusion_flutter_charts: ^24.1.41
  syncfusion_flutter_gauges: ^24.1.41
  pin_code_fields: ^8.0.1
  dropdown_button2: ^2.3.9
  dotted_border: ^2.1.0
  extended_text: ^13.0.0

  # cicd
  sentry_flutter: ^7.14.0
  device_info_plus: ^9.1.2
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  flutter_native_splash: ^2.4.0

dev_dependencies:
  # testing
  flutter_test:
    sdk: flutter

  # analysis
  flutter_lints: ^2.0.3
  analyzer: ^6.2.0
  custom_lint: ^0.5.11
  riverpod_lint: ^2.3.7

  # codegen
  build_runner: ^2.4.6
  freezed: ^2.4.2
  riverpod_generator: ^2.3.9
  flutter_gen_runner: ^5.3.1
  json_serializable: ^6.7.1
  go_router_builder: ^2.3.2
  path_provider: any
dependency_overrides:
  flutter_gen_core:
    git:
      url: https://github.com/FlutterGen/flutter_gen.git
      ref: 8c57b5aa73f7793d614f064ec8e00434cc4cf01a
      path: packages/core

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/vectors/
    - assets/illustrations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: rubik
      fonts:
        - asset: assets/fonts/rubik-variable-font-wght.ttf
        - asset: assets/fonts/rubik-italic-variable-font-wght.ttf
          style: italic
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_gen:
  output: lib/src/gen/
  integrations:
    flutter_svg: true

flutter_native_splash:
  image: assets/images/splash.gif
  color: "#FFFFFF"
  android: true
  ios: true
