name: hadar_program
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  #dev
  logger: ^2.0.2

  # state
  hooks_riverpod: ^2.4.0
  flutter_hooks: ^0.20.1
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.0.0
  bot_toast: ^4.1.1

  # routing
  go_router: ^10.1.2

  # networking
  dio: ^5.3.2
  http: ^1.1.0 # todo: remove

  # integrations
  flutter_svg: ^2.0.7

  # icons
  fluentui_system_icons: ^1.1.215

  # widgets
  flutter_easyloading: ^3.0.5 # todo: remove
  pin_code_fields: ^8.0.1
  dropdown_button2: ^2.3.9
  
dev_dependencies:
  # testing
  flutter_test:
    sdk: flutter

  # analysis
  flutter_lints: ^2.0.3
  analyzer: ^6.2.0
  custom_lint: ^0.5.3
  riverpod_lint: ^2.0.4

  # codegen
  build_runner: ^2.4.6
  freezed: ^2.4.2
  riverpod_generator: ^2.3.2
  flutter_gen_runner: ^5.3.1
  json_serializable: ^6.7.1
  # go_router_builder: ^2.3.1 # todo: 2.3.1 incompatible with analyzer 6

dependency_overrides:
  flutter_gen_core:
    git:
      url: https://github.com/FlutterGen/flutter_gen.git
      ref: 8c57b5aa73f7793d614f064ec8e00434cc4cf01a
      path: packages/core

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: rubik
      fonts:
        - asset: assets/fonts/rubik-variable-font-wght.ttf
        - asset: assets/fonts/rubik-italic-variable-font-wght.ttf
          style: italic
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_gen:
  output: lib/src/gen/
  integrations:
    flutter_svg: true