name: hadar_program
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # native
  file_picker: ^5.5.0
  url_launcher: ^6.1.14
  http_parser: ^4.0.2
  flutter_local_notifications: ^15.1.1
  file_saver: ^0.2.13

  # location
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  image_picker: ^1.0.2

  # state
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.5
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  bot_toast: ^4.1.3
  skeletonizer: ^1.3.0

  # util
  collection: ^1.18.0
  timeago: ^3.6.1
  faker: ^2.1.0
  kosher_dart: ^2.0.16

  # routing
  go_router: ^14.1.4

  # networking
  dio: ^5.4.3+1
  requests_inspector: ^4.0.3
  http: ^1.1.0 # todo: remove

  # integrations
  rxdart: ^0.27.7
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  widget_to_marker: ^1.0.5
  timezone: ^0.9.2
  flutter_timezone: ^1.0.7

  # icons
  fluentui_system_icons: ^1.1.241

  # widgets
  flutter_easyloading: ^3.0.5 # todo: remove
  syncfusion_flutter_charts: ^26.1.35
  syncfusion_flutter_gauges: ^26.1.35
  pin_code_fields: ^8.0.1
  dropdown_button2: ^2.3.9
  dotted_border: ^2.1.0
  extended_text: ^13.0.2 # only used in 1 place (report_details_screen.dart)

  # cicd
  logger: ^2.3.0
  sentry_flutter: ^8.2.0
  device_info_plus: ^10.1.0
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  flutter_native_splash: ^2.4.0
  pointer_interceptor: ^0.10.1+1

dev_dependencies:
  # testing
  flutter_test:
    sdk: flutter

  # analysis
  flutter_lints: ^4.0.0
  analyzer: 6.4.1
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

  # codegen
  build_runner: ^2.4.11
  freezed: ^2.5.2
  riverpod_generator: ^2.4.0
  flutter_gen_runner: ^5.5.0+1
  json_serializable: ^6.8.0
  go_router_builder: ^2.7.0
  flutter_launcher_icons: ^0.13.1
  
dependency_overrides:
  # flutter_gen_core:
  #   git:
  #     url: https://github.com/FlutterGen/flutter_gen.git
  #     ref: 8c57b5aa73f7793d614f064ec8e00434cc4cf01a
  #     path: packages/core
  kosher_dart:
    git:
      url: https://github.com/noga-dev/kosher_dart.git
      ref: master

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/illustrations/
    - assets/animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: rubik
      fonts:
        - asset: assets/fonts/rubik-variable-font-wght.ttf
        - asset: assets/fonts/rubik-italic-variable-font-wght.ttf
          style: italic
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_gen:
  output: lib/src/gen/
  integrations:
    flutter_svg: true

flutter_native_splash:
  image: assets/images/splash.gif
  color: "#FFFFFF"
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
