{
   "header":{
      "recordType":"000001",
      "fileCreationTimestamp":"19/04/2024 13:36:54"
   },
   "records":[
      {
         "release":14,
         "version":2,
         "dataRecordFormat":2,
         "tsNumber":7,
         "releaseIdExtention":0,
         "payload":{
            "genericRecord":{
               "recordType":"OCSChargingRecord",
               "recordElements":[
                  {
                     "varName":"prevMeName",
                     "varValue":"ig-charging-5f7dbcb489-8q56q"
                  },
                  {
                     "varName":"recordId",
                     "varValue":"20240416093833_18dcfad1-3914-4e88-bf4c-d3ab3b092dd3"
                  },
                  {
                     "varName":"generationTimestamp",
                     "varValue":"16/04/2024 09:38:33"
                  },
                  {
                     "varName":"sessionId",
                     "varValue":"uk5109yr.dc-dublin.de;1713138831;2338"
                  },
                  {
                     "varName":"serviceContextId",
                     "varValue":"32274@3gpp.org"
                  },
                  {
                     "varName":"requestType",
                     "varValue":"INITIAL_REQUEST"
                  },
                  {
                     "varName":"sessionSequenceNumber",
                     "varValue":"0"
                  },
                  {
                     "varName":"sessionStartTime",
                     "varValue":"16/04/2024 09:38:33"
                  },
                  {
                     "varName":"dayOfWeek",
                     "varValue":"Tuesday"
                  },
                  {
                     "varName":"originHost",
                     "varValue":"uk5109yr.dc-dublin.de"
                  },
                  {
                     "varName":"deviceId",
                     "varValue":"447493473915"
                  },
                  {
                     "varName":"deviceName",
                     "varValue":"447493473915"
                  },
                  {
                     "varName":"deviceOwner",
                     "varValue":"447493473915"
                  },
                  {
                     "varName":"deviceOwnerName",
                     "varValue":"447493473915"
                  },
                  {
                     "varName":"deviceState",
                     "varValue":"VF_ACTIVE"
                  },
                  {
                     "varName":"devicePartitionId",
                     "varValue":"1"
                  },
                  {
                     "varName":"deviceSiteId",
                     "varValue":"1"
                  },
                  {
                     "varName":"isOnNet",
                     "varValue":"false"
                  },
                  {
                     "varName":"classOfServiceCode",
                     "varValue":"10"
                  },
                  {
                     "varName":"classOfService",
                     "varValue":"CS_VF_MBB"
                  },
                  {
                     "varName":"cuProfile",
                     "varValue":"VF_STANDARD"
                  },
                  {
                     "varName":"defaultTariffPlan",
                     "varValue":"TP_VF_MBB"
                  },
                  {
                     "varName":"enhancedRequestingSystem",
                     "varValue":"JDO"
                  },
                  {
                     "varName":"accountID",
                     "varValue":"447493473915"
                  },
                  {
                     "varName":"accountType",
                     "varValue":"PRE_PAID"
                  },
                  {
                     "varName":"Account_PLC",
                     "varValue":"VF_ACTIVE"
                  },
                  {
                     "varName":"Account_ELC",
                     "varValue":"ACTIVE"
                  },
                  {
                     "varName":"roamingIndicator",
                     "varValue":"HOME"
                  },
                  {
                     "varName":"causeForRecClosing",
                     "varValue":"0"
                  },
                  {
                     "varName":"resultCode",
                     "varValue":"2001"
                  },
                  {
                     "varName":"recordOpeningTime",
                     "varValue":"16/04/2024 09:38:33"
                  },
                  {
                     "varName":"recordClosureTime",
                     "varValue":"16/04/2024 09:38:33"
                  },
                  {
                     "varName":"duration",
                     "varValue":"0"
                  },
                  {
                     "varName":"recordSequenceNumber",
                     "varValue":"1"
                  },
                  {
                     "varName":"meHostName",
                     "varValue":"cnigxom01;ig-charging-5f7dbcb489-8q56q"
                  },
                  {
                     "varName":"nccVersion",
                     "varValue":"SPS_23_2_R1"
                  },
                  {
                     "varName":"RecordTimestamp",
                     "varValue":"16/04/2024 09:38:33"
                  }
               ],
               "recordExtensions":[
                  {
                     "recordProperty":"listOfSubscriptionID",
                     "recordSubExtensions":[
                        {
                           "recordProperty":"subscriptionId",
                           "recordElements":[
                              {
                                 "varName":"subscriptionIdType",
                                 "varValue":"0"
                              },
                              {
                                 "varName":"subscriptionIdData",
                                 "varValue":"447493473915"
                              }
                           ]
                        }
                     ]
                  },
                  {
                     "recordProperty":"listOfMscc",
                     "recordSubExtensions":[
                        {
                           "recordProperty":"mscc",
                           "recordElements":[
                              {
                                 "varName":"serviceIdentifier",
                                 "varValue":"4408643"
                              },
                              {
                                 "varName":"chargingType",
                                 "varValue":"ONLINE_CHARGING"
                              },
                              {
                                 "varName":"recordEventType",
                                 "varValue":"SMS"
                              },
                              {
                                 "varName":"firstDataStart",
                                 "varValue":"16/04/2024 09:38:33"
                              },
                              {
                                 "varName":"grantedUnits",
                                 "varValue":"7"
                              },
                              {
                                 "varName":"usageType",
                                 "varValue":"MONEY"
                              },
                              {
                                 "varName":"validityTime",
                                 "varValue":"1800"
                              },
                              {
                                 "varName":"resultCode",
                                 "varValue":"2001"
                              },
                              {
                                 "varName":"recordEventResult",
                                 "varValue":"11"
                              },
                              {
                                 "varName":"subRecordEventType",
                                 "varValue":"ECUR"
                              },
                              {
                                 "varName":"localSequenceNumber",
                                 "varValue":"1"
                              }
                           ],
                           "recordSubExtensions":[
                              {
                                 "recordProperty":"deviceInfo",
                                 "recordSubExtensions":[
                                    {
                                       "recordProperty":"subscriptionInfo",
                                       "recordElements":[
                                          {
                                             "varName":"subscriptionId",
                                             "varValue":"d562eb10-8819-40ea-8cd1-2dd076d8ca51"
                                          },
                                          {
                                             "varName":"subscriptionState",
                                             "varValue":"Active"
                                          },
                                          {
                                             "varName":"bundleName",
                                             "varValue":"TP_VF_MBB"
                                          },
                                          {
                                             "varName":"bundleVersion",
                                             "varValue":"1"
                                          },
                                          {
                                             "varName":"bundleActivationType",
                                             "varValue":"NORMAL"
                                          },
                                          {
                                             "varName":"accountID",
                                             "varValue":"447493473915"
                                          },
                                          {
                                             "varName":"accountName",
                                             "varValue":"447493473915"
                                          },
                                          {
                                             "varName":"subscriptionStartDateTime",
                                             "varValue":"16/04/2024 09:23:17"
                                          },
                                          {
                                             "varName":"subscriptionEndDateTime",
                                             "varValue":"14/07/2024 23:00:00"
                                          }
                                       ],
                                       "recordSubExtensions":[
                                          {
                                             "recordProperty":"chargingServiceInfo",
                                             "recordElements":[
                                                {
                                                   "varName":"chargingServiceName",
                                                   "varValue":"ECUR_Default_CL1"
                                                },
                                                {
                                                   "varName":"chargingServiceType",
                                                   "varValue":"MONEY"
                                                },
                                                {
                                                   "varName":"chargingServicePriority",
                                                   "varValue":"5400"
                                                },
                                                {
                                                   "varName":"chargingServiceCategory",
                                                   "varValue":"PTP/DTP"
                                                },
                                                {
                                                   "varName":"chargingServiceVersion",
                                                   "varValue":"1"
                                                },
                                                {
                                                   "varName":"chargingServicePatchVersion",
                                                   "varValue":"null"
                                                }
                                             ],
                                             "recordSubExtensions":[
                                                {
                                                   "recordProperty":"accountInfo",
                                                   "recordElements":[
                                                      {
                                                         "varName":"accountID",
                                                         "varValue":"447493473915"
                                                      },
                                                      {
                                                         "varName":"accountName",
                                                         "varValue":"447493473915"
                                                      },
                                                      {
                                                         "varName":"accountType",
                                                         "varValue":"PRE_PAID"
                                                      },
                                                      {
                                                         "varName":"accountOwner",
                                                         "varValue":"447493473915"
                                                      },
                                                      {
                                                         "varName":"accountState",
                                                         "varValue":"ACTIVE"
                                                      },
                                                      {
                                                         "varName":"accountBalanceBefore",
                                                         "varValue":"10.000000"
                                                      },
                                                      {
                                                         "varName":"accountBalanceAfter",
                                                         "varValue":"10.000000"
                                                      },
                                                      {
                                                         "varName":"accountOveragelimit",
                                                         "varValue":"0.000000"
                                                      },
                                                      {
                                                         "varName":"accountBalanceCommitted",
                                                         "varValue":"0.000000"
                                                      },
                                                      {
                                                         "varName":"accountBalanceReserved",
                                                         "varValue":"7.000000"
                                                      },
                                                      {
                                                         "varName":"loanStateAfter",
                                                         "varValue":"INITIAL"
                                                      },
                                                      {
                                                         "varName":"rateId",
                                                         "varValue":"ECUR_Rate"
                                                      },
                                                      {
                                                         "varName":"tariffID",
                                                         "varValue":"ECUR_Default_CL1_ChargingRules"
                                                      },
                                                      {
                                                         "varName":"secondaryCostCommitted",
                                                         "varValue":"0.000000"
                                                      }
                                                   ]
                                                }
                                             ]
                                          }
                                       ]
                                    },
                                    {
                                       "recordProperty":"counterInfo",
                                       "recordElements":[
                                          {
                                             "varName":"counterName",
                                             "varValue":"PS1"
                                          },
                                          {
                                             "varName":"counterKey",
                                             "varValue":"2c32efbe-1de3-4a3f-85cf-99085fcf2e11"
                                          },
                                          {
                                             "varName":"counterType",
                                             "varValue":"MULTI_BUNDLE"
                                          },
                                          {
                                             "varName":"counterUnitType",
                                             "varValue":"Money"
                                          },
                                          {
                                             "varName":"counterKindOfUnit",
                                             "varValue":"MONEY"
                                          },
                                          {
                                             "varName":"alignGranularity",
                                             "varValue":"TRUE"
                                          },
                                          {
                                             "varName":"counterValueBefore",
                                             "varValue":"0.000000"
                                          },
                                          {
                                             "varName":"counterValueAfter",
                                             "varValue":"0.000000"
                                          },
                                          {
                                             "varName":"subscriptionId",
                                             "varValue":"249cda25-0c7f-454a-bad6-2e3ef28a29b2"
                                          },
                                          {
                                             "varName":"chargingServicePriority",
                                             "varValue":"400"
                                          }
                                       ]
                                    }
                                 ]
                              }
                           ]
                        }
                     ]
                  }
               ]
            }
         }
      }
   ],
   "trailer":{
      "recordType":"999999",
      "recordCount":"46"
   }
}